version: '3'
services:
  postgres:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: react-golang-movies-app
    volumes:
      - react-go-movies-app-postgres-data:/var/lib/postgresql/data
      - ./react_go_movies_seed.sql:/docker-entrypoint-initdb.d/react_go_movies_seed.sql
    networks:
      - app-network

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - postgres
    ports:
      - '8080:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - react-go-movies-app-pgadmin:/root/.pgadmin
    networks:
      - app-network

volumes:
  react-go-movies-app-postgres-data:
  react-go-movies-app-pgadmin:
networks:
  app-network:
    driver: bridge
